complexity:
  TooManyFunctions:
    ignoreAnnotatedFunctions:
      - Preview

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    ignoreAnnotated:
      - Preview
